<?php require('template/header.phtml') ?>

<h3>Welcome to the DVD rental shop </h3>

<h3>Renting DVD's</h3>
<p>You may use the website to rent DVD's and check the currently rented products. You may browse through the
    different DvD's that are available by type, genre and title. You must create an account, in-order to rent
    to rent any of the item from our store.</p>

<?php require('template/footer.phtml') ?>
