<?php require ('template/header.phtml') ?>
<div class="container">
    <div class="page-header">
        <h2>Login</h2>
        <p>Please log in-order to rent DVD's</p>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form action="login.php" method="post">

                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" name="email" class="form-control">
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" name="password" class="form-control">
                </div>

                <button class="btn btn-default" type="submit">Login</button>

            </form>
            <p>If you are not registered <a href="../registration.php">click here</a> to create an account</p>
        </div>
    </div>
</div>


<?php if(isset($view->error)) : ?>
    <p><?php echo $view->error; ?></p>
<?php endif; ?>

<?php require ('template/footer.phtml')?>
