<?php require ('template/header.phtml') ?>

<div class="container">
    <div class="page-header">
        <h2>Register</h2>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form action="registration.php" method="post">

                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" name="email" id="email" class="form-control" >
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>

                <div class="form-group">
                    <label for="password2">Confirm Password:</label>
                    <input type="password" name="password2" class="form-control">
                </div>

                <div class="form-group">
                    <label for="address">Address</label>
                    <input type="text" name="address" id="address"  class="form-control">
                </div>

                <div class="form-group">
                    <label for="phone">Phone number:</label>
                    <input type="text" name="phone" id="number" class="form-control">
                </div>

                <button class="btn btn-default" type="submit">Register</button>

            </form>
            <p>Create an account in-order to rent DVD's. If you already have an account <a href="../login.php">click here</a>  to login</p>
        </div>
    </div>

</div>



<?php if(isset($view->error)) : ?>
 <p><?php echo $view->error; ?></p>
<?php endif; ?>

<?php require ('template/footer.phtml')?>
