<?php require ('template/header.phtml') ?>


    <h1>Register</h1>
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

            <p>Enter your details to create an account. If you already have an account <a href="../login.php"> click
                    here</a>
            to log in.</p>

            <label>Username</label><br>
            <input type="text" name="username" value="<?php echo $_POST['username'];?>" size="10" maxlength="10"/><br>

            <label>Password</label><br>
            <input type="password" name="password" value=""/><br>

            <label>Re-enter Password</label><br>
            <input type="password" name="password2" value=""/><br>

            <label>Email</label><br>
            <input type="text" name="email" value="<?php echo $_POST['email'];?>"/><br>

            <label>Phone Number</label><br>
            <input type="text" name="number" value="<?php echo $_POST['number'];?>"/><br>

            <br>
                <input type="submit" value="submit" name="submit" />
                <input type="reset" value="reset" name="reset"/>

        </form>

<?php if(isset($view->error)) : ?>
 <p><?php echo $view->error; ?></p>
<?php endif; ?>

<?php require ('template/footer.phtml')?>
